---
kind: pipeline
type: docker
name: renovate

trigger:
  event:
    - cron
    - push
    - custom

environment:
  LOG_LEVEL: debug

steps:
  - name: renovate - validate config
    image: renovate/renovate:35.159.7
    # https://github.com/renovatebot/renovate/discussions/15049
    commands:
      # - unset GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL
      - renovate-config-validator

  - name: renovate
    image: renovate/renovate:35.159.7
    # https://github.com/renovatebot/renovate/discussions/15049
    commands:
      # - unset GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL
      - renovate

    environment:
      RENOVATE_TOKEN:
        from_secret: RENOVATE_TOKEN
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      GITHUB_COM_USER:
        from_secret: GITHUB_USER
      GITHUB_COM_TOKEN:
        from_secret: GITHUB_TOKEN
      DOCKER_LSCR_IO_USERNAME:
        from_secret: GITHUB_USER
      DOCKER_LSCR_IO_PASSWORD:
        from_secret: GITHUB_TOKEN
      DOCKER_GHRC_IO_USERNAME:
        from_secret: GITHUB_USER
      DOCKER_GHCR_IO_PASSWORD:
        from_secret: GITHUB_TOKEN
---
kind: secret
name: RENOVATE_TOKEN
get:
  path: doppler-drone
  name: RENOVATE_TOKEN
---
kind: secret
name: GITHUB_USER
get:
  path: doppler-drone
  name: GITHUB_USER
---
kind: secret
name: GITHUB_TOKEN
get:
  path: doppler-drone
  name: GITHUB_TOKEN
---
kind: secret
name: DOCKER_USER
get:
  path: doppler-drone
  name: DOCKER_USER
---
kind: secret
name: DOCKER_PASSWORD
get:
  path: doppler-drone
  name: DOCKER_PASSWORD
