---
kind: pipeline
type: docker
name: renovate

trigger:
  branch:
    - main
  event:
    - cron
    - custom
    - push

environment:
  LOG_LEVEL: debug

steps:
  - name: renovate - validate config
    image: renovate/renovate:36.64
    commands:
      - renovate-config-validator

  - name: renovate
    image: renovate/renovate:36.64
    commands:
      - renovate
    environment:
      RENOVATE_TOKEN:
        from_secret: RENOVATE_TOKEN
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      GITHUB_COM_USER:
        from_secret: GITHUB_USER
      GITHUB_COM_TOKEN:
        from_secret: RENOVATE_GITHUB_TOKEN
      DOCKER_LSCR_IO_USERNAME:
        from_secret: GITHUB_USER
      DOCKER_LSCR_IO_PASSWORD:
        from_secret: RENOVATE_GITHUB_TOKEN
      DOCKER_GHRC_IO_USERNAME:
        from_secret: GITHUB_USER
      DOCKER_GHCR_IO_PASSWORD:
        from_secret: RENOVATE_GITHUB_TOKEN
    when:
      status: [success]
      event: [cron, custom]

  - name: discord notification
    image: appleboy/drone-discord
    settings:
      username: Drone
      webhook_id:
        from_secret: DRONE_DISCORD_ID
      webhook_token:
        from_secret: DRONE_DISCORD_TOKEN
      message: >
        {{#success build.status}}✅{{else}}⚠️{{/success}}
        repo: `[{{repo.name}}/{{commit.branch}}]` `[{{uppercase build.event}}]` [[#{{build.number}}]({{build.link}})][[{{truncate commit.sha 5}}]({{commit.link}})]
               commit: `{{commit.message}}`
---
kind: secret
name: RENOVATE_TOKEN
get:
  path: doppler-drone
  name: RENOVATE_TOKEN
---
kind: secret
name: GITHUB_USER
get:
  path: doppler-drone
  name: GITHUB_USER
---
kind: secret
name: GITHUB_TOKEN
get:
  path: doppler-drone
  name: GITHUB_TOKEN
---
kind: secret
name: DOCKER_USER
get:
  path: doppler-drone
  name: DOCKER_USER
---
kind: secret
name: DOCKER_PASSWORD
get:
  path: doppler-drone
  name: DOCKER_PASSWORD
---
kind: secret
name: DRONE_DISCORD_ID
get:
  path: doppler-drone
  name: DRONE_DISCORD_ID
---
kind: secret
name: DRONE_DISCORD_TOKEN
get:
  path: doppler-drone
  name: DRONE_DISCORD_TOKEN
